apiVersion: apps/v1
kind: Deployment
metadata:
  name: ml-on-cluster
spec:
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
      - name: ml-on-cloud-app-container
        image: indranil0603/ml-on-cloud-app:1.0.0
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 5000
